# Exercise 1: Convert NP-Arrays to Tensors

This was a notebook of last years ML class. There we used numpy, but you should easily be able to convert the code to Tensorflow.

<b>One-dimensional Array</b>

In [3]:
import tensorflow as tf
a = tf.constant([1, 2, 3])              # Create a rank 1 array
print('Type:', type(a))              # Prints "<class 'numpy.ndarray'>"
print('Shape:', a.shape)             # Prints "(3,)"

# Task:
# Now print the contents in the form "Contents:[1 2 3]"
print(a)
print("[{} {} {}]".format(a[0],a[1],a[2]))


Type: <class 'tensorflow.python.framework.ops.EagerTensor'>
Shape: (3,)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
[1 2 3]


In [4]:
# Dooing some modification
a= tf.Variable(a)
a[0].assign(5)                             # Change an element of the array
print('After Modification', a)       # Prints "[5 2 3]"

After Modification [5 2 3]


<b>Two-dimensional Array</b>

In [5]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
b = tf.constant(b)
print(b.shape)                     # Prints "(2, 3)"
print(b)                           
print([[1,2,3],[4,5,6]])

(2, 3)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
[[1, 2, 3], [4, 5, 6]]


<b>Vector/Matrix Creation</b>

In [9]:
x = tf.Variable(tf.ones((10,10), dtype=tf.int64));
x[5,5].assign(5)
print(x)
print(tf.zeros(10))


# also multidimensional arrays possible

<tf.Variable 'Variable:0' shape=(10, 10) dtype=int64, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 5, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)>
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [11]:
# create a diagonal matrix
tf.eye(7,dtype = tf.int64)

<tf.Tensor: shape=(7, 7), dtype=int64, numpy=
array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int64)>

In [13]:
#for a in range(6):
#  print(a)
print(tf.range(6))


tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)
[0 1 2 3 4 5]


In [18]:
d = tf.reshape(tf.Variable((tf.range(6)+1)), (2,3))
print(d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<b>Elementwise Addition / Equals</b>

In [20]:
tf.constant([1, 2, 3])+tf.constant([10, 20, 30])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 22, 33])>

In [22]:
tf.constant([1, 2, 3])+10

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 12, 13])>

In [23]:
tf.reshape(tf.constant([1, 2, 3,4]),(2,2))==np.ones(2)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True, False],
       [False, False]])>

In [24]:
tf.constant([1, 2, 3])==3

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([False, False,  True])>

<b> Hamarad Product - Elementwise Multiplication</b>

$$
\begin{bmatrix}
  1 & 2 & 3\\
  4 & 5 & 6\\
\end{bmatrix} \odot 
\begin{bmatrix}
  1 & 2 & 3\\
  4 & 5 & 6\\
\end{bmatrix} = 
\begin{bmatrix}
  1 & 4 & 9\\
  16 & 25 & 36\\
\end{bmatrix}
$$

In [25]:
d*d# Hadamard product - Elementwise Multiplication

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

$$
\begin{bmatrix}
  1 & 2 & 3\\
  4 & 5 & 6\\
\end{bmatrix} \odot 
\begin{bmatrix}
  1 \\ 2 \\ 3\\
\end{bmatrix} = 
\begin{bmatrix}
  1 & 4 & 9\\
  4 & 10 & 18\\
\end{bmatrix}
$$

In [27]:
# Elementwise multiplication with different shapes
d*tf.constant([1,2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [ 4, 10, 18]])>

$$
\begin{bmatrix}
  1 & 2 & 3\\
  4 & 5 & 6\\
\end{bmatrix} \odot 
\begin{bmatrix}
  2\\
\end{bmatrix} = 
\begin{bmatrix}
  2 & 4 & 6\\
  8 & 10 & 12\\
\end{bmatrix}
$$

In [28]:
(d*tf.constant([2]))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

<b> Matrix Multiplication - dot product </b>

$$
\begin{bmatrix}
  1 & 2 & 3\\
  4 & 5 & 6\\
\end{bmatrix} \cdot 
\begin{bmatrix}
  1\\
  2\\
  3\\
\end{bmatrix} = 
\begin{bmatrix}
  14\\
  32\\
\end{bmatrix}
$$

In [33]:
# Matrix Multiplication # dot product
e = tf.tensordot(d, tf.constant([1,2,3]),1)
e

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([14, 32])>

$$
\begin{bmatrix}
  1 & 2 & 3\\
  4 & 5 & 6\\
\end{bmatrix} \cdot 
\begin{bmatrix}
  1 & 4\\
  2 & 5\\
  3 & 6\\
\end{bmatrix}
 = 
\begin{bmatrix}
  14 & 32\\
  32 & 77\\
\end{bmatrix}
$$

In [34]:
f = tf.tensordot(d, tf.transpose(d),1)
print(f)

tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)
